name: Github Contributions Data Update

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contributions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx tsx scripts/update/update.ts

          git diff --cached --quiet || git commit -m "Update contributions"

          git push
