name: Github Contributions Data Update

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contributions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx tsx scripts/update/update.ts

      - name: Git Push
        run: |
          git config user.name "github-actions[activity-updater]"
          git config user.email "bot@shada.me"

          git add .
          git diff --cached --quiet && exit 0

          git commit -m "chore: update data"
          git push
